### ISSUE TITLE
 can not talk with the NPC.

### ISSUE THREAD

**Issue by diamonderion** [noidexe/top-down-action-rpg-template#1]
can not talk with the NPC. and can not open inventory , can you teach me how to get the quest from the NPC,thanks

**Comment by noidexe** [comment]
Check the InputMap in project settings. The inventory appear when the action "pause" is pressed. To get the quest you use the "interact" action. I think it's Esc and E respectively. On gamepads, pause and Circle/Xbox B/Nintendo A

**Comment by chrisleewoo** [comment]
Where in the assets can I find the actual text of the dialog boxes? I am really at a loss to find it.

**Comment by noidexe** [comment]
@chrisleewoo in the scenes where the NPCs are spawned. NPC.gd exports an array of strings that you can use to add dialogs from the inspector, and there is a Quest.tscn node you can attach to NPCs to turn them into quest givers that also exports.
You can type text identifiers and use translations files to have all the text in one place or modify NPC.gd to use your own dialog files instead of an exported array. The Dialogs singleton is independent and you can send whatever text you want to it.
